<a href="https://colab.research.google.com/github/saumya8b-dev/awesome-website/blob/main/imggen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#fruit image generator
#people can generate fruit images like apple, banana, mango etc etc
#1: acquire a lot of fruit pics and label them
#2: clean the data
#3:create an image generation model
#4: train and test the model
#5: improve model
#but first learn to build a neural network at all

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('sample_data/mnist_train_small.csv', header = None)
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]/255.0

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]/255.0

def init_params():
  W1 = np.random.rand(10, 784)-0.5
  B1 = np.random.rand(10, 1)-0.5
  W2 = np.random.rand(10, 10)-0.5
  B2 = np.random.rand(10, 1)-0.5
  return W1, B1, W2, B2

def ReLU(Z):
  return np.maximum(0, Z)
def softmax(Z):
    # Subtracting the max prevents np.exp() from hitting Infinity (inf)
    exp_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True))

    # Normalise column-by-column across classes
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)
def one_hot(Y):
  one_hot_Y = np.zeros((Y.size, Y.max() + 1))
  one_hot_Y[np.arange(Y.size), Y] = 1
  return one_hot_Y.T

def forward_prop(W1, B1, W2, B2, X):
  Z1 = W1.dot(X) + B1
  A1 = ReLU(Z1)
  Z2 = W2.dot(A1) + B2
  A2 = softmax(Z2)
  return Z1, A1, Z2, A2
def deriv_ReLU(Z):
    return Z>0
def back_prop(Z1, A1, Z2, A2, W2, X, Y ):
  one_hot_Y = one_hot(Y)
  dZ2 = A2 - one_hot_Y
  dW2 = 1/m * dZ2.dot(A1.T)
  dB2 = 1/m * np.sum(dZ2)
  dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
  dW1 = 1/m * dZ1.dot(X.T)
  dB1 = 1/m * np.sum(dZ1)
  return dW1, dB1, dW2, dB2
def update_params(W1, B1, W2, B2, dW1, dB1, dW2, dB2, alpha):
  W1 = W1 - (alpha * dW1)
  B1 = B1 - (alpha * dB1)
  W2 = W2 - (alpha * dW2)
  B2 = B2 - (alpha * dB2)
  return W1, B1, W2, B2
def get_predictions(A2):
  return np.argmax(A2, 0)
def get_accuracy(predictions, Y):
  print(predictions, Y)
  return np.sum(predictions == Y)/Y.size
def gradient_descent(X, Y, iterations, alpha):
  W1, B1, W2, B2 = init_params()
  for i in range(iterations):
    Z1, A1, Z2, A2 = forward_prop(W1, B1, W2, B2, X)
    dW1, dB1, dW2, dB2 = back_prop(Z1, A1, Z2, A2, W2, X, Y )
    W1, B1, W2, B2 = update_params(W1, B1, W2, B2, dW1, dB1, dW2, dB2, alpha)
    if i% 50 == 0:
      print('Iteration: ', i)
      print('Accuracy: ', get_accuracy(get_predictions(A2), Y))
  return W1, B1, W2, B2
W1, B1, W2, B2 = gradient_descent(X_train, Y_train, 500, 0.1)

Iteration:  0
[5 1 1 ... 5 5 0] [8 5 0 ... 1 4 6]
Accuracy:  0.08926315789473684
Iteration:  50
[5 5 0 ... 5 1 0] [8 5 0 ... 1 4 6]
Accuracy:  0.35189473684210526
Iteration:  100
[8 5 0 ... 1 1 6] [8 5 0 ... 1 4 6]
Accuracy:  0.5727368421052632
Iteration:  150
[8 5 0 ... 1 8 6] [8 5 0 ... 1 4 6]
Accuracy:  0.6945789473684211
Iteration:  200
[8 5 0 ... 1 8 6] [8 5 0 ... 1 4 6]
Accuracy:  0.7483157894736842
Iteration:  250
[8 5 0 ... 1 8 6] [8 5 0 ... 1 4 6]
Accuracy:  0.7792105263157895
Iteration:  300
[8 5 0 ... 1 4 6] [8 5 0 ... 1 4 6]
Accuracy:  0.8028947368421052
Iteration:  350
[8 5 0 ... 1 4 6] [8 5 0 ... 1 4 6]
Accuracy:  0.8191578947368421
Iteration:  400
[8 5 0 ... 1 4 6] [8 5 0 ... 1 4 6]
Accuracy:  0.8300526315789474
Iteration:  450
[8 5 0 ... 1 4 6] [8 5 0 ... 1 4 6]
Accuracy:  0.8396842105263158


In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load and shuffle dataset
data = pd.read_csv('sample_data/mnist_train_small.csv', header = None)
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

# Split and transpose data
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n] / 255.0  # Normalized

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n] / 255.0  # Normalized

def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    B1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    B2 = np.random.rand(10, 1) - 0.5
    return W1, B1, W2, B2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    exp_Z = np.exp(Z - np.max(Z, axis=0, keepdims=True))  # Safe against overflow
    return exp_Z / np.sum(exp_Z, axis=0, keepdims=True)

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    return one_hot_Y.T

def forward_prop(W1, B1, W2, B2, X):
    Z1 = W1.dot(X) + B1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + B2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def deriv_ReLU(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    m_samples = X.shape[1]
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1/m_samples * dZ2.dot(A1.T)
    dB2 = 1/m_samples * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1/m_samples * dZ1.dot(X.T)
    dB1 = 1/m_samples * np.sum(dZ1, axis=1, keepdims=True)
    return dW1, dB1, dW2, dB2

def update_params(W1, B1, W2, B2, dW1, dB1, dW2, dB2, alpha):
    W1 = W1 - (alpha * dW1)
    B1 = B1 - (alpha * dB1)
    W2 = W2 - (alpha * dW2)
    B2 = B2 - (alpha * dB2)
    return W1, B1, W2, B2

def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, B1, W2, B2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, B1, W2, B2, X)
        dW1, dB1, dW2, dB2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, B1, W2, B2 = update_params(W1, B1, W2, B2, dW1, dB1, dW2, dB2, alpha)
        if i % 50 == 0:
            print('Iteration: ', i)
            print('Accuracy: ', get_accuracy(get_predictions(A2), Y))
    return W1, B1, W2, B2

# Run training
W1, B1, W2, B2 = gradient_descent(X_train, Y_train, 500, 0.1)


Iteration:  0
Accuracy:  0.13405263157894737
Iteration:  50
Accuracy:  0.5756842105263158
Iteration:  100
Accuracy:  0.6910526315789474
Iteration:  150
Accuracy:  0.7457894736842106
Iteration:  200
Accuracy:  0.7782631578947369
Iteration:  250
Accuracy:  0.7988421052631579
Iteration:  300
Accuracy:  0.8141052631578948
Iteration:  350
Accuracy:  0.8258947368421052
Iteration:  400
Accuracy:  0.835
Iteration:  450
Accuracy:  0.8423157894736842
